[package]
name = "dictionary"
version.workspace = true
edition.workspace = true
publish.workspace = true
authors.workspace = true
description = "dictionary host function"

[dependencies]
reactor = { path = "../reactor" }
async-trait = {workspace = true}

[lints]
workspace = true
