[package]
name = "http-backend"
version.workspace = true
edition.workspace = true
publish.workspace = true
authors.workspace = true
description = "Client component for outbound http requests"

[dependencies]
reactor = { path = "../reactor" }
http = {workspace = true}
async-trait = {workspace = true}
anyhow = {workspace = true}
tracing = {workspace = true}
hyper = { workspace = true }
tokio = { workspace = true }
pin-project = "1.1.3"
log = "0.4.20"
url = "2.5.0"

[dev-dependencies]
claims = "0.7"
tracing-test = "0.2"
mock-http-connector = "0.3"