name: Continuous Delivery

permissions:
  pull-requests: write
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload:
    name: Build and upload

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-wasi
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.2.1

      - name: Release build
        run: cargo build --release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ASSET }}