name: Continuous Delivery

on:
  pull_request:
    types:
      - closed

env:
  CARGO_TERM_COLOR: always

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged

