name: Continuous Integration

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust
        uses: actions-rs/toolchain@stable
        with:
          profile: minimal
          target: wasm32-wasi

      - name: Run Release PR
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}
    needs: release
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --bin cli

      - name: Upload target binary
        uses: actions/upload-artifact@v4
        with:
          name: cli-${{ matrix.os }}
          path: target/release/cli