name: Continuous Delivery

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - 'main'
env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-wasi

      - name: Run Release PR
        uses: MarcoIeni/release-plz-action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: release
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-wasi
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.2.1

      - name: Release build
        run: cargo build --release

      - name: Upload target binary
        uses: actions/upload-artifact@v4
        with:
          name: cli-${{ matrix.os }}
          path: target/release/cli